version: '3.7'

services:
  questdb:
    image: questdb/questdb:7.3.7
    container_name: questdb
    restart: always
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
    volumes:
      - ./questdb:/var/lib/questdb
    environment:
      - QDB_LOG_W_STDOUT_LEVEL=INFO
      - QDB_LOG_W_FILE_LEVEL=INFO
      - QDB_LOG_W_HTTP_MIN_LEVEL=INFO
      - QDB_SHARED_WORKER_COUNT=2 # Amount of worker threads
      - QDB_PG_USER=postgres # postgresql user -> Configured in .env file
      - QDB_PG_PASSWORD=postgres # postgresql password -> Configured in .env file
      - QDB_TELEMETRY_ENABLED=false # Disable telemetry

      ## Additional variables can be found here: https://questdb.io/docs/reference/configuration